### ISSUE TITLE
EPG fails to load programmes if channels are not specified

### ISSUE THREAD

**Issue by noquierouser** [afedchin/xbmc-addon-iptvsimple#47]
According to the [XMLTV DTD](http://xmltv.cvs.sourceforge.net/viewvc/xmltv/xmltv/xmltv.dtd), `channel` elements are not mandatory for a valid XMLTV Document.

In fact, a document can have only `channel` elements, only `programme` elements or `channel` and `programme` elements, but only if `channel` elements come before `programme` elements.

While trying the add-on with a `programme`-only Document, it fails to load EPG, but it loads a `channel`-only Document perfectly.

**Comment by afedchin** [comment]
The `channel` section is required for properly map between channel name in m3u and XMLTV.
